# 无量纲化

## 1、归一化

In [36]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
data=[[-1,2],[-0.5,6],[0,10],[1,19]]

In [45]:
# 归一化
scaler=MinMaxScaler() #实例化
scaler=scaler.fit(data) # fit，本质生成min(x),max(x)
result=scaler.transform(data) # 通过接口导出结果
result

array([[0.        , 0.        ],
       [0.25      , 0.23529412],
       [0.5       , 0.47058824],
       [1.        , 1.        ]])

In [38]:
# 标准化
scaler2=StandardScaler() # 实例化
scaler2.fit(data) # fit，本质生成方差和均值
x_std=scaler2.transform(data) #通过接口导出结果
print(scaler2.mean_)
print(scaler2.var_)

[-0.125  9.25 ]
[ 0.546875 39.6875  ]


In [46]:
# 训练、导出结果一步达成
result1_=scaler1.fit_transform(data)
result1_

array([[ 5.        ,  5.        ],
       [ 6.25      ,  6.17647059],
       [ 7.5       ,  7.35294118],
       [10.        , 10.        ]])

In [47]:
# 归一化的结果逆转回去
scaler.inverse_transform(result_)

array([[-1.  ,  2.  ],
       [-0.5 ,  6.25],
       [ 0.  , 10.5 ],
       [ 1.  , 19.  ]])

In [48]:
# 使用MinMaxScaler的参数feature_range实现数据归一化到[0,1]以外的范围
scaler=MinMaxScaler(feature_range=[5,10])
result=scaler.fit_transform(data)
result

array([[ 5.        ,  5.        ],
       [ 6.25      ,  6.17647059],
       [ 7.5       ,  7.35294118],
       [10.        , 10.        ]])

In [43]:
# 归一化的结果逆转
scaler1.inverse_transform(result1)

## 数据特征多时，fit会报错，表示数据量太大无法计算，
## 可以用partial_fit作为训练接口
## scaler=scaler.partial_fit(data),result=scaler.transform(data)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 19. ]])

In [20]:
## 利用numpy实现归一化 ,计算效率不会高于sklearn
import numpy as np
x=np.array([[-1,2],[-0.5,6],[0,10],[1,18]])
x_nor=(x-x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))
x_nor 

[[-1.   2. ]
 [-0.5  6. ]
 [ 0.  10. ]
 [ 1.  18. ]]


In [17]:
# 逆转归一化
x_returned=x_nor*(x.max(axis=0)-x.min(axis=0))+x.min(axis=0)
x_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

## 2、标准化

In [49]:
from sklearn.preprocessing import StandardScaler
data=[[-1,2],[-0.5,6],[0,10],[1,19]]

scaler=StandardScaler() # 实例化
scaler.fit(data) # fit，本质生成方差和均值
x_std=scaler.transform(data) #通过接口导出结果
print(scaler.mean_)
print(scaler.var_)

[-0.125  9.25 ]
[ 0.546875 39.6875  ]


In [32]:
x_std

array([[-1.18321596, -1.1508299 ],
       [-0.50709255, -0.51588926],
       [ 0.16903085,  0.11905137],
       [ 1.52127766,  1.54766779]])

In [33]:
x_std.mean()

0.0

In [34]:
x_std.std()

1.0

In [35]:
scaler.fit_transform(data)
scaler.inverse_transform(x_std)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 19. ]])

 # 缺失值

In [50]:
import pandas as pd 
# index_col=0表示作为行标签的列
data=pd.read_csv(r"/Users/songhaiyue/Documents/课件/03数据预处理和特征工程/Narrativedata【瑞客论坛 www.ruike1.com】.csv",index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [51]:
# 可以看到Age、Sembarked有缺失
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         714 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [57]:
Age=data.loc[:,"Age"].values.reshape(-1,1) ## sklearn中特征矩阵必须是二维，利用reshape升维
Age[:10]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [nan],
       [54.],
       [ 2.],
       [27.],
       [14.]])

In [58]:
from sklearn.impute import SimpleImputer # 缺失值处理模块
imp_mean=SimpleImputer() ##实例化，用均值填补
imp_median=SimpleImputer(strategy="median") # 实例化，用中位数填补
imp_0=SimpleImputer(strategy="constant",fill_value=0) # 实例化，用0填补

imp_mean=imp_mean.fit_transform(Age)
imp_median=imp_median.fit_transform(Age)
imp_0=imp_0.fit_transform(Age)

In [59]:
imp_mean[:10]

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ]])

In [60]:
imp_median[:10]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [28.],
       [54.],
       [ 2.],
       [27.],
       [14.]])

In [61]:
imp_0[:10]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [ 0.],
       [54.],
       [ 2.],
       [27.],
       [14.]])

In [62]:
data.loc[:,"Age"]=imp_median 
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [63]:
# 使用众数填补Embarked 
Embarked=data.loc[:,"Embarked"].values.reshape(-1,1)
imp_mode=SimpleImputer(strategy="most_frequent")
data.loc[:,"Embarked"]=imp_mode.fit_transform(Embarked)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    891 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


### 使用pandas和numpy进行填补

In [76]:
import pandas as pd 
import numpy as np
# index_col=0表示作为行标签的列
data=pd.read_csv(r"/Users/songhaiyue/Documents/课件/03数据预处理和特征工程/Narrativedata【瑞客论坛 www.ruike1.com】.csv",index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [78]:
# data.loc[:,"Age"]=data.loc[:,"Age"].fillna(data.loc[:,"Age"].median()) # 使用中位数进行填补，在DataFrame中直接进行填补
data.loc[:,"Age"]=data.loc[:,"Age"].fillna(data.loc[:,"Age"].mode()) # 使用众数进行填补，在DataFrame中直接进行填补
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [68]:
data.loc[:,"Age"][:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    28.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [66]:
# .dropna(axis=0)删除所有缺失值的行，.dropna(axis=1)删除所有缺失值的列
# inplace=True表示在原数据集上进行修改，默认false，表示生成一个复制对象
data.dropna(axis=0,inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 4 columns):
Age         889 non-null float64
Sex         889 non-null object
Embarked    889 non-null object
Survived    889 non-null object
dtypes: float64(1), object(3)
memory usage: 34.7+ KB


## 查看缺失值的分布

In [69]:
import pandas as pd 
import numpy as np
# index_col=0表示作为行标签的列
data=pd.read_csv(r"/Users/songhaiyue/Documents/课件/03数据预处理和特征工程/Narrativedata【瑞客论坛 www.ruike1.com】.csv",index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [72]:
data.isnull().sum()

Age    Sex  Embarked  Survived
0    False  False     False     False
1    False  False     False     False
2    False  False     False     False
3    False  False     False     False
4    False  False     False     False
..     ...    ...       ...       ...
886  False  False     False     False
887  False  False     False     False
888   True  False     False     False
889  False  False     False     False
890  False  False     False     False

[891 rows x 4 columns]

In [71]:
data.isnull().sum(axis=1)

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    1
889    0
890    0
Length: 891, dtype: int64